version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: opencv:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: 3.4
    upstream: opencv:3.4        # Required. Can be a branch in the same forked repo.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
